pipeline {
    agent any

    stages {
        stage('Install Yarn') {
            steps{
                echo "Installing yarn..."
                sh 'sudo curl -fsSL https://deb.nodesource.com/setup_14.x | bash -'
                sh 'sudo apt-get install -y nodejs'
                sh 'sudo npm install -g yarn@1.22.17'
            }
        }
        
        stage('Install dependency') {
            steps{
                sh 'yarn'
            }
        }
        stage('yarn build') {
            steps{
                    sh 'yarn prettier'
                    sh 'yarn build'
            }
        }

        // stage('artifact to s3') {
        //     steps{
        //     s3Upload consoleLogLevel: 'INFO', dontSetBuildResultOnFailure: false, dontWaitForConcurrentBuildCompletion: false, entries: [[bucket: 'fe-quick-learner-jenkins', excludedFile: '', flatten: false, gzipFiles: false, keepForever: false, managedArtifacts: false, noUploadOnFailure: false, selectedRegion: 'ap-southeast-2', showDirectlyInBrowser: false, sourceFile: 'build/**', storageClass: 'STANDARD', uploadFromSlave: false, useServerSideEncryption: false]], pluginFailureResultConstraint: 'FAILURE', profileName: 'fe-quick-learner-jenkins', userMetadata: []
        //     }
        // }
        
    }

    post {
        always {
            echo 'One way or another, I have finished'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'Test succeeded!'
        }
        unstable {
            echo 'Test unstable :/'
        }
        failure {
            echo 'Test failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
    
}