pipeline {
    agent {
        docker {
            image 'node:14.17.0'
        }
    }

    environment { 
        HOME="."
        BUILD_ARTIFACT_PATH='/var/jenkins_home/workspace/GoExport_FE/build'
        BUCKET_NAME='goexpert-frontend' 
    }

    stages {
        stage('Install Yarn') {
            steps{
                echo "Installing yarn..."
                // sh 'sudo -A curl -fsSL https://deb.nodesource.com/setup_14.x | bash -'
                // sh 'sudo apt-get install -y nodejs'
                // sh 'npm install -g yarn@1.22.17'
                sh 'npm --version'
                sh 'ls'
                // sh 'chown -R jenkins ~/.npm'
                sh 'npm install'
            }
        }
        
        stage('Build') {
            steps{
                echo "Building..."
                sh 'npm run build'
            }
        }
        stage('Install AWS CLI') {
            when {
                expression { currentBuild.result == null || currentBuild.result == 'SUCCESS' }
            }
            steps {
                echo "Installing AWS CLI ..."
                sh 'apt-get update'
                sh 'apt install python3-pip -y'
                sh 'pip3 install awscli --upgrade'
            }
        }

        stage('deployToS3') {
            steps {
                            echo "Deploying to S3..."
            withAWS(credentials: 'aws', region: 'ap-southeast-2') {
                    sh 'aws s3 cp "${BUILD_ARTIFACT_PATH}" "${BUCKET_NAME}" --recursive --acl public-read'
                }
            }

        }
        
    }
    



    post {
        always {
            echo 'One way or another, I have finished'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'Test succeeded!'
        }
        unstable {
            echo 'Test unstable :/'
        }
        failure {
            echo 'Test failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
    
}